package manejoDeConstrucciones.comandos;

public enum ConstruccionesDisponibles {
	BARRACA,
	FABRICA,
	PUERTOESTELAR,
	ARCHIVOSTEMPLARIOS,
	ACCESO,
	ASIMILADOR,
	PORTALESTELAR,
	CENTRODEMINERAL,
	DEPOSITODESUMINISTROS,
	REFINERIA,
	PILON,
	NEXOMINERAL
}
