package unidades;

public enum Parametros {
    ENERGIAACTUAL,
    ENERGIATOTAL,
    REGENERACIONDEENERGIA,
    VIDAACTUAL,
    VIDATOTAL,
    REGENERACIONDEVIDA, AEREO, TERRESTRE, RANGO, RANGOAEREO, RANGOTERRESTRE, CAPACIDADTRANSPORTE, CAPACIDADACTUAL,
}
