package excepciones;

import excepciones.construicciones.ExcepcionNoSePuedeEntrenarUnidad;

public class ExcepcionNoSePuedeEntrenarUnidadPorRecursosInsuficientes extends ExcepcionNoSePuedeEntrenarUnidad {
}
