package excepciones;

import excepciones.construicciones.ExcepcionNoSePuedeEntrenarUnidad;

public class ExcepcionNoSePuedeEntrenarUnidadPorSuministrosInsuficientes extends ExcepcionNoSePuedeEntrenarUnidad {
}
