package modelo.interfaces;

/*
-INTERFAZ QUE PERMITE MOSTRAR UN MENSAJE

-LAS EXCEPCIONES QUE DEBEN SER AGARRADAS POR LA INTERFAZ GRAFICA DEBEN HEREDAR DE ESTE METODO PARA PODER MOSTRAR
SU CONTENIDO
 */

public interface Mostrable {
    String mostrarMensaje();
}
